### ISSUE TITLE
Название репозитория

### ISSUE THREAD

**Issue by AMD-NICK** [Be1zebub/GMD-Mods#1]
GMD это сокращенное название сервиса приема платежей. Т.е. по сути сам сайт, который может "модить" только команда GMD

IGS - внутриигровой интерфейс. Его может модить как угодно кто угодно. 

Название репозитория подразумевает как бы модификации для самого сайта, что в целом некорректно и нелогично, учитывая наполнение репозитория

Рекомендую переименовать репозиторий в IGS-Mods. GitHub сделает автоматический редирект с текущего названия на новое, если кто-то перейдет по старой ссылке

**Comment by Be1zebub** [comment]
GMD знают все, про IGS почти ни кто не слышал.
К тому-же ты и сам используешь название GMD для телеграмм канала посвящённого модификациям IGS
![image](https://user-images.githubusercontent.com/34854689/172397288-67685f42-e779-49cd-b593-5dc46560adcd.png)

**Comment by AMD-NICK** [comment]
> GMD знают все, про IGS почти ни кто не слышал.
> К тому-же ты и сам используешь название GMD для телеграмм канала посвящённого модификациям IGS
> ![image](https://user-images.githubusercontent.com/34854689/172397288-67685f42-e779-49cd-b593-5dc46560adcd.png)

не стоит повторять мои ошибки. Сейчас смена названия репозитория ничего не стоит и ничем не чревата

**Comment by moriokii** [comment]
лол, он не обязан что-то менять, он использовал сокращения трех слов, то что сервис так называеться ничего не значит, это не какое-то уникальное название зарегестрировано за три пизды

**Comment by Be1zebub** [comment]
> не стоит повторять мои ошибки   

Я считаю что название IGS было ошибкой, GMD и IGS это одна общая инфраструктура которая друг без друга не работает - какой смысл пытаться их разделить тогда?
GMD для людей понятнее, менять ничего не буду.
