### ISSUE TITLE
cashback problem

### ISSUE THREAD

**Issue by opuruhaji** [Be1zebub/GMD-Mods#10]
![image](https://user-images.githubusercontent.com/59743591/213653180-e19f70fd-aef2-4b46-b14d-c7138129c20f.png)

так же, из-за этого выдает такую ошибку:
![image](https://user-images.githubusercontent.com/59743591/213653280-231395e8-84d2-40a9-81f9-8c2810612740.png)

**Comment by opuruhaji** [comment]
tts так же создает такие проблемы

**Comment by Be1zebub** [comment]
solved, протестируй на сервере
https://github.com/Be1zebub/GMD-Mods/commit/a8fbcc2a291d0a3728c063c1c19915127d39557f
о tts по подробнее...

**Comment by opuruhaji** [comment]
спасибо, кешбек теперь раблотает.
насчет tts — ошибку так же прекратило выдавать, но текст не проигрывается.

**Comment by Be1zebub** [comment]
хз, тестируй - если найдёшь причино следственную связь создай pr/issue
