### ISSUE TITLE
Вопрос по кешбеку

### ISSUE THREAD

**Issue by BazZziliuS** [Be1zebub/GMD-Mods#4]
https://github.com/Be1zebub/GMD-Mods/blob/master/garrysmod/addons/igs-modification/lua/igs/mods/cashback.lua

Можешь рассказать как его настроить? Если точнее то как сделать месячный кешбек и 10% от суммы покупки
И если не трудно обнови тему https://forum.gm-donate.net/t/keshbek/963

**Comment by Be1zebub** [comment]
> Можешь рассказать как его настроить? Если точнее то как сделать месячный кешбек и 10% от суммы покупки  

в конце файла есть пример создания предмета
https://github.com/Be1zebub/GMD-Mods/blob/855a00c58985c7e348210b1d85adee3163bf593b/garrysmod/addons/igs-modification/lua/igs/mods/cashback.lua#L54-L55
подобные примеры использования есть в каждом модуле.

> И если не трудно обнови тему https://forum.gm-donate.net/t/keshbek/963  

что именно там обновить? ссылку разве что?

**Comment by BazZziliuS** [comment]
Просто на форуме написано что можно сделать кешбек сразу на все и я подумал что тут тоже можно это сделать

**Comment by Be1zebub** [comment]
На форуме более старая версия, в новой версии нет возможности создания глобального кэшбэка.
Сделал апдейт
https://github.com/Be1zebub/GMD-Mods/commit/61707dd91d6f3dd43abcc883f1f94b263e89f8ad
пример активации глобального кэшбэка смотри в конце файла.
